version: "3.9"

services:
  backend:
    build: .
    container_name: django-drf
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
     - 8000:8000
    volumes:
     - .:/core
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A config worker -l INFO
    volumes:
     - .:/core
    depends_on:
      - redis
      - backend

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  postgres:
    image: postgres:14-alpine
    container_name: posg
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres



volumes:
  smtp4dev-data:
  postgres_data:
