# Generated by Django 5.0.4 on 2024-05-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialservice',
            options={'ordering': ['-created_at']},
        ),
    ]
