# Generated by Django 5.0.4 on 2024-05-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_team_facebook_team_instagram_team_linkdin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='services'),
        ),
    ]
