# Generated by Django 4.2 on 2024-07-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='profile',
        ),
    ]
