# Generated by Django 4.2 on 2024-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
