# Generated by Django 4.2 on 2024-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='id_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
